name: Deploy to Vercel (Prod) and Smoke Test

on:
  # Evitar deploy duplicado, rodar manualmente quando quiser smoke + deploy
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Build (sanity check)
        run: npm run build --if-present

      - name: Deploy to Vercel (Production)
        id: vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-args: '--yes'
          prod: true

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Smoke check /api/status on production alias
        env:
          PROD_ALIAS: https://quiz.qigongbrasil.com
        run: |
          echo "Checking $PROD_ALIAS/api/status"
          curl -fsSL "$PROD_ALIAS/api/status" | tee status.json
          jq -e '.environment=="production"' status.json

      - name: Optional E2E: submit + webhook
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          PROD_ALIAS: https://quiz.qigongbrasil.com
          TEST_PHONE: "11998457676"
        run: |
          echo 'Triggering submit...'
          curl -fsSL -H "Content-Type: application/json" \
            -d '{
              "lead": {"NOME": "CI Test Prod", "EMAIL": "ci@test.example", "CELULAR": "(11) 99845-7676"},
              "respostas": {"P1": "B", "P2": ["A"], "P3": "C", "P4": ["D"], "P5": "B", "P6": "C", "P7": "B", "P8": "B", "P9": "B", "P10": "D", "P11": "E", "P12": "A", "P13": "C"}
            }' \
            "$PROD_ALIAS/api/submit" | tee submit.json
          jq -e '.success==true' submit.json

          echo 'Triggering webhook...'
          curl -fsSL -H "Content-Type: application/json" \
            -d '{"phone": "'$TEST_PHONE'", "name": "CI Test Webhook"}' \
            "$PROD_ALIAS/api/webhook/unnichat/ver-resultados" | tee webhook.json
          jq -e '.success==true' webhook.json
